import WebampLazy from "../../webamp/js/webampLazy";
import type { IMetadataApi } from "../../webamp/js/types";
import { TRANSMISSIONS, WordBand } from "./transmissions";
import { EQ_LAYOUT, HIDE_EQ_EXTRAS } from "./cosmetics";
import type { EqBand } from "./webampAdapter";
import {
  clearMarqueeMessage,
  restoreUnlockedTrack,
  createReadoutKeeper,
  enableManualTuning,
  lockWindowDragOnTouch,
  keepChannelLightsLit,
  layoutEqBands,
  sizePlaylist,
  setBandIdle,
  onStateSlice,
  placeWindows,
  setDoubleSize,
  setMarqueeMessage,
  silentTrackUrl,
} from "./webampAdapter";
import { createDesktop } from "./shell/desktop";
import { createDialup } from "./shell/dialup";
import { createProgress } from "./progress";
import { remove } from "./storage";
import { STORY_KEY } from "./shell/narrative";
import { createDisplayProperties } from "./shell/display";
import { createNarrative } from "./shell/narrative";
import {
  RunningTransmission,
  runTransmission,
  transmissionTrackLabel,
} from "./runTransmission";

// Which EQ slider is the tuning dial. Must be in EQ_LAYOUT, or the
// player can't reach it.
const TUNER_BAND = 600;

const TRANSMISSION_HINTS = [
  matchMedia("(pointer: coarse)").matches
    ? "SCAN: TAP A SLIDER, SWIPE TO TUNE  *  HOLD STEADY TO LOCK"
    : "SCAN: DRAG OR WHEEL TUNE  *  HOLD STEADY TO LOCK",
  "NOISE FILTER ON  *  FOLLOW THE WARNING TO CLEAR IT",
  "NOISE FILTER ON  *  THE TARGET IS ON THE OTHER SIDE THIS TIME",
  "NOISE FILTER ON  *  THE TARGET IS NARROWER THIS TIME",
  "SIX WORDS  *  NARROW NOISE TARGET  *  STEADY HANDS",
  "NOISE + CLARITY FILTERS  *  CLEAR BOTH TO LOCK",
];

// Module-level state for cleanup on unload
let runningTx: RunningTransmission | null = null;

async function main() {
  const webampNode = document.getElementById("webamp-mount") as HTMLDivElement;
  // Visually hidden live region: Webamp's widgets are bitmaps, so this is
  // what screen readers hear.
  const statusReadout = document.getElementById(
    "status-readout"
  ) as HTMLDivElement;

  const webamp = new WebampLazy({
    enableDoubleSizeMode: true,
    // Generated by scripts/build_placeholder_skin.py until the real skin exists.
    initialSkin: { url: "/skins/signal-tuner-placeholder.wsz" },
    availableSkins: [
      { url: "/skins/signal-tuner-placeholder.wsz", name: "Signal Tuner" },
    ],
    requireJSZip: () => import("jszip").then((mod) => mod.default),
    requireMusicMetadata: () =>
      import("music-metadata") as unknown as Promise<IMetadataApi>,
  });
  await webamp.renderInto(webampNode);
  layoutEqBands(EQ_LAYOUT, { hideExtras: HIDE_EQ_EXTRAS });
  lockWindowDragOnTouch();
  enableManualTuning(
    webamp,
    Object.keys(EQ_LAYOUT).map(Number) as EqBand[],
    TUNER_BAND,
    { dialBand: TUNER_BAND }
  );
  // @ts-ignore debugging hook
  window.__webamp = webamp;

  // Native 2x (crisp, and drags track the cursor) wherever the desktop has
  // room: playlist stacked under main + EQ, or beside them on short screens.
  // 1x on anything smaller.
  // Re-places windows only when the size tier changes, so a resize doesn't
  // undo windows the player has dragged; Webamp keeps them on screen itself.
  let layoutTier: string | null = null;
  const layoutPlayer = () => {
    const { clientWidth: w, clientHeight: h } = webampNode;
    const x = w < 760 ? Math.max(0, Math.round((w - 275) / 2)) : 112;
    const y = 12;
    // Stacked needs main + EQ at 2x plus a six-row playlist underneath.
    const stacked2x = w >= 760 && h >= 650;
    const beside2x = !stacked2x && w >= 950 && h >= 490;
    const tier = stacked2x ? "stacked" : beside2x ? "beside" : "small";
    if (tier === layoutTier) return;
    layoutTier = tier;
    setDoubleSize(webamp, stacked2x || beside2x);
    sizePlaylist(webamp, stacked2x, stacked2x ? 1 : beside2x ? 2 : 1);
    if (stacked2x) {
      placeWindows(webamp, {
        main: { x, y },
        equalizer: { x, y: y + 232 },
        playlist: { x, y: y + 464 },
      });
    } else if (beside2x) {
      placeWindows(webamp, {
        main: { x, y },
        equalizer: { x, y: y + 232 },
        playlist: { x: x + 558, y },
      });
    } else {
      placeWindows(webamp, {
        main: { x, y },
        equalizer: { x, y: y + 116 },
        playlist: { x, y: y + 232 },
      });
    }
  };
  layoutPlayer();

  const desktop = createDesktop({
    winamp: {
      mount: webampNode,
      onMinimize: (cb) => webamp.onMinimize(cb),
      onClose: (cb) =>
        webamp.onWillClose((cancel) => {
          cancel();
          cb();
        }),
    },
  });

  createDisplayProperties({ close: desktop.close });
  // Music credits: the in-game names are puns, so the real recordings are
  // credited here, as their licences require.
  const credited = TRANSMISSIONS.flatMap((t) => (t.unlockTrack ? [t.unlockTrack] : []));
  (document.getElementById("credits-text") as HTMLElement).textContent =
    "MUSIC CREDITS\n\n" +
    credited
      .map(
        (t) =>
          `"${t.title}" by ${t.artist}\n  is "${t.original.title}"\n  by ${t.original.composer}` +
          (t.original.licence ? `\n  licence: ${t.original.licence}` : "")
      )
      .join("\n\n") +
    "\n\nCC BY 4.0: https://creativecommons.org/licenses/by/4.0/\n" +
    "Kevin MacLeod: https://incompetech.com";
  const narrative = createNarrative(desktop);
  const dialup = createDialup({
    onConnected: narrative.connect,
    showWindow: desktop.open,
    hideWindow: desktop.close,
  });
  (document.getElementById("reset-item") as HTMLElement).onclick = () => {
    desktop.closeStart();
    if (!confirm("Erase every decoded transmission and start over?")) return;
    savedProgress.reset();
    remove(STORY_KEY);
    location.reload();
  };
  (document.getElementById("redial-item") as HTMLElement).onclick = () => {
    desktop.closeStart();
    dialup.redial();
  };

  const readouts = createReadoutKeeper(webamp);
  keepChannelLightsLit(webamp);

  // The playlist is the transmission list. Rows point at a silent clip until
  // their song is unlocked, so the real file is never fetched early.
  const initialTracks = TRANSMISSIONS.map((tx, idx) => ({
    url: silentTrackUrl(),
    defaultName: `${idx + 1}. Signal Tuner - ${tx.title}`,
    metaData: transmissionTrackLabel(tx),
    duration: tx.unlockTrack?.lengthSeconds ?? 180,
  }));
  webamp.appendTracks(initialTracks);
  const savedProgress = createProgress(TRANSMISSIONS);
  TRANSMISSIONS.forEach((tx, idx) => {
    if (savedProgress.isCompleted(tx.id) && tx.unlockTrack != null) {
      restoreUnlockedTrack(webamp, idx, tx.unlockTrack);
      readouts.setTrackLabel(idx, {
        artist: tx.unlockTrack.artist,
        title: tx.unlockTrack.title,
      });
    } else {
      const found = new Set(savedProgress.decodedBands(tx.id));
      readouts.setTrackLabel(
        idx,
        transmissionTrackLabel(tx, (b) => found.has(b.id))
      );
    }
  });
  // Pick up at the first transmission still to solve.
  const firstUnsolved = TRANSMISSIONS.findIndex((t) => !savedProgress.isCompleted(t.id));
  const resumeIndex = firstUnsolved === -1 ? TRANSMISSIONS.length - 1 : firstUnsolved;

  const initialPlaylistState = webamp.store.getState();
  if (initialPlaylistState.playlist.trackOrder.length > 0) {
    webamp.store.dispatch({
      type: "BUFFER_TRACK",
      id: initialPlaylistState.playlist.trackOrder[resumeIndex],
    });
  }

  let currentTxIndex = resumeIndex;
  let isUncleared = false;
  let currentUnclearedNames: string[] = [];
  let currentLockedWord: string | null = null;
  let currentLockBand: WordBand | null = null;
  let currentLockProgress: number = 0;
  const completedTransmissions = new Set<number>(
    TRANSMISSIONS.flatMap((t, i) => (savedProgress.isCompleted(t.id) ? [i] : []))
  );

  const updateStatusDisplay = () => {
    const tx = TRANSMISSIONS[currentTxIndex];
    if (isUncleared) {
      statusReadout.textContent = `${currentUnclearedNames.join(" and ")} interference. Follow the warning to bring the ${currentUnclearedNames.length > 1 ? "filters" : "filter"} into range and clear the static.`;
    } else if (
      currentLockBand != null &&
      currentLockProgress > 0 &&
      currentLockProgress < 1
    ) {
      // No percentage: the live region should speak once per lock, not on
      // every animation frame.
      statusReadout.textContent = "Locking onto a station. Hold still.";
    } else if (currentLockedWord != null) {
      statusReadout.textContent = `Station "${currentLockedWord}" locked.`;
    } else {
      statusReadout.textContent = tx.title;
    }
  };

  // Night clock on the player's time digits: 3:14 AM, two minutes later for
  // every word found across all transmissions.
  const wordsFound = new Set<string>(
    TRANSMISSIONS.flatMap((t, i) =>
      t.bands
        .filter(
          (b) => savedProgress.isCompleted(t.id) || savedProgress.decodedBands(t.id).includes(b.id)
        )
        .map((b) => `${i}:${b.word}`)
    )
  );
  const totalWords = TRANSMISSIONS.reduce((n, t) => n + t.bands.length, 0);
  const dawn = document.getElementById("dawn") as HTMLElement;
  const showClock = () => {
    // 3:14 AM to 4:00 AM across every word in the game.
    const minutes = Math.round(3 * 60 + 14 + (46 * wordsFound.size) / totalWords);
    readouts.set({ timeSeconds: minutes });
    dawn.style.opacity = String(Math.min(1, wordsFound.size / totalWords));
    const mm = String(minutes % 60).padStart(2, "0");
    desktop.setClock(`${Math.floor(minutes / 60)}:${mm} AM`);
  };
  showClock();

  const startTx = (index: number) => {
    runningTx?.stop();
    currentTxIndex = index;
    const transmission = TRANSMISSIONS[index];
    currentLockedWord = null;
    currentLockBand = null;
    currentLockProgress = 0;
    isUncleared = false;
    currentUnclearedNames = [];

    // Stop playback if switching to a transmission that isn't yet completed
    if (!completedTransmissions.has(index)) {
      webamp.stop();
    }

    updateStatusDisplay();

    // Only the sliders this transmission uses are bright.
    for (const band of Object.keys(EQ_LAYOUT).map(Number) as EqBand[]) {
      setBandIdle(
        band,
        band !== TUNER_BAND && !transmission.layers?.some((l) => l.band === band)
      );
    }

    runningTx = runTransmission(webamp, transmission, {
      tunerBand: TUNER_BAND,
      trackIndex: index,
      readouts,
      proximityFeedback: true,
      introHint: TRANSMISSION_HINTS[index],
      // A solved transmission replays from scratch.
      decodedBandIds: completedTransmissions.has(index)
        ? []
        : savedProgress.decodedBands(transmission.id),
      completeHint:
        index < TRANSMISSIONS.length - 1
          ? "[OK] DECODED  *  PRESS >>| FOR NEXT TRANSMISSION"
          : "[OK] ALL TRANSMISSIONS DECODED",
      onLockedBand: (word) => {
        currentLockedWord = word;
        updateStatusDisplay();
      },
      onLockProgress: (band, progress) => {
        currentLockBand = band;
        currentLockProgress = progress;
        updateStatusDisplay();
      },
      onInterferenceChange: (cleared, unclearedNames) => {
        isUncleared = !cleared;
        currentUnclearedNames = unclearedNames;
        updateStatusDisplay();
        if (!cleared) narrative.onGameEvent({ type: "interference" });
      },
      onDecode: (word, count) => {
        wordsFound.add(`${index}:${word}`);
        showClock();
        narrative.onGameEvent({
          type: "decode",
          transmission: index,
          count,
          total: transmission.bands.length,
        });
        const game = runningTx?.game;
        if (game != null && !completedTransmissions.has(index)) {
          savedProgress.setDecoded(
            transmission.id,
            transmission.bands.filter((b) => game.isBandDecoded(b.id)).map((b) => b.id)
          );
        }
        const line = transmissionTrackLabel(transmission, (b) =>
          game ? game.isBandDecoded(b.id) : false
        ).title;
        statusReadout.textContent = `Found "${word}". ${count} of ${transmission.bands.length}: ${line}`;
      },
      onComplete: () => {
        const firstTime = !completedTransmissions.has(index);
        completedTransmissions.add(index);
        savedProgress.complete(transmission.id);
        if (firstTime) {
          narrative.onGameEvent({
            type: "complete",
            transmission: index,
            last: index === TRANSMISSIONS.length - 1,
          });
        }
        const track = transmission.unlockTrack;
        statusReadout.textContent = track
          ? `Transmission complete. Unlocked "${track.title}" by ${track.artist}.`
          : "Transmission complete.";
      },
    });

    // Replaying a solved transmission keeps its row showing the song.
    const track = transmission.unlockTrack;
    if (completedTransmissions.has(index) && track != null) {
      readouts.setTrackLabel(index, { artist: track.artist, title: track.title });
    }
  };

  // Wire player controls (>>|, |<<, double click) to switch transmissions
  onStateSlice(
    webamp,
    (w) => {
      const s = w.store.getState();
      return s.playlist.currentTrack == null
        ? -1
        : s.playlist.trackOrder.indexOf(s.playlist.currentTrack);
    },
    (newIdx) => {
      if (
        newIdx >= 0 &&
        newIdx < TRANSMISSIONS.length &&
        newIdx !== currentTxIndex
      ) {
        startTx(newIdx);
      }
    }
  );

  // Wire playlist single-click selection to switch transmissions and buffer track
  onStateSlice(
    webamp,
    (w) => w.store.getState().playlist.lastSelectedIndex,
    (newIdx) => {
      if (newIdx != null && newIdx >= 0 && newIdx < TRANSMISSIONS.length) {
        const s = webamp.store.getState();
        const trackId = s.playlist.trackOrder[newIdx];
        if (trackId != null && s.playlist.currentTrack !== trackId) {
          webamp.store.dispatch({ type: "BUFFER_TRACK", id: trackId });
        }
        if (newIdx !== currentTxIndex) {
          startTx(newIdx);
        }
      }
    }
  );

  // Guard against playing undecoded transmissions before completion
  onStateSlice(
    webamp,
    (w) => w.store.getState().media.status,
    (status) => {
      if (status === "PLAYING" && !completedTransmissions.has(currentTxIndex)) {
        webamp.stop();
        setMarqueeMessage(
          webamp,
          `TRANSMISSION ${currentTxIndex + 1} ENCRYPTED - TUNE TO DECODE`
        );
      }
    }
  );

  startTx(resumeIndex);

  window.addEventListener("resize", layoutPlayer);
  dialup.start();

  const resumeAudio = () => {
    const ctx = webamp.media.getAnalyser().context;
    if (ctx instanceof AudioContext && ctx.state === "suspended") {
      ctx.resume().catch((err: unknown) => {
        console.warn("AudioContext resume failed:", err);
      });
    }
  };
  // A touch's pointerdown doesn't count as a user gesture for audio, so keep
  // trying on release too until the context is running.
  for (const type of ["pointerdown", "pointerup", "touchend"]) {
    window.addEventListener(type, resumeAudio, true);
  }

  window.addEventListener("beforeunload", () => {
    runningTx?.stop();
    clearMarqueeMessage(webamp);
  });
}

main();
