name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.0
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: npx turbo build
        env:
          NODE_ENV: production
      - name: Lint and type-check
        run: npx turbo lint type-check
      - name: Test
        run: npx turbo test -- --maxWorkers=2
        env:
          NODE_ENV: test
